global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
### START MANAGED BY ANSIBLE
  - job_name: 'prometheus_auth'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
{% for node_exporter in groups['node_exporters'] %}
      - targets: ['{{ hostvars[node_exporter]['inventory_hostname'] }}:9100']
{% endfor %} 
    basic_auth:
      username: "{{ prom_username }}"
      password: "{{ prom_password }}"
### END MANAGED BY ANSIBLE